# https://taskfile.dev

version: '3'

vars:
  PROTO_DIR: ../../proto/edition

tasks:
  build:
    cmds: 
    - protoc --proto_path={{.PROTO_DIR}} --go_out=. --go_opt=module=productinfo/service product_info.proto --go-grpc_out=. --go-grpc_opt=module=productinfo/service
    - go build
  run:
    cmds:
      - go run .
