// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order_management.proto

package ecommerce

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Price         *float32               `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty"`
	Destination   *string                `protobuf:"bytes,5,opt,name=destination" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_management_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Order) GetPrice() float32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Order) GetDestination() string {
	if x != nil && x.Destination != nil {
		return *x.Destination
	}
	return ""
}

var File_order_management_proto protoreflect.FileDescriptor

const file_order_management_proto_rawDesc = "" +
	"\n" +
	"\x16order_management.proto\x12\tecommerce\x1a\x1egoogle/protobuf/wrappers.proto\"\x87\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination2S\n" +
	"\x0fOrderManagement\x12@\n" +
	"\fsearchOrders\x12\x1c.google.protobuf.StringValue\x1a\x10.ecommerce.Order0\x01B\x1fZ\x1dproductinfo/service/ecommerceb\beditionsp\xe8\a"

var (
	file_order_management_proto_rawDescOnce sync.Once
	file_order_management_proto_rawDescData []byte
)

func file_order_management_proto_rawDescGZIP() []byte {
	file_order_management_proto_rawDescOnce.Do(func() {
		file_order_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_management_proto_rawDesc), len(file_order_management_proto_rawDesc)))
	})
	return file_order_management_proto_rawDescData
}

var file_order_management_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_management_proto_goTypes = []any{
	(*Order)(nil),                  // 0: ecommerce.Order
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_order_management_proto_depIdxs = []int32{
	1, // 0: ecommerce.OrderManagement.searchOrders:input_type -> google.protobuf.StringValue
	0, // 1: ecommerce.OrderManagement.searchOrders:output_type -> ecommerce.Order
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_management_proto_init() }
func file_order_management_proto_init() {
	if File_order_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_management_proto_rawDesc), len(file_order_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_management_proto_goTypes,
		DependencyIndexes: file_order_management_proto_depIdxs,
		MessageInfos:      file_order_management_proto_msgTypes,
	}.Build()
	File_order_management_proto = out.File
	file_order_management_proto_goTypes = nil
	file_order_management_proto_depIdxs = nil
}
